sentences = [
    "Dnes ráno jsem šel do obchodu koupit čerstvý chléb a dva jogurty.",
    "Večer si rád čtu knihu, kterou mi doporučila moje starší sestra.",
    "Auto na parkovišti pískalo, protože baterie byla slabá a stará.",
    "Mohu ti půjčit svůj deštník, když venku prší a fouká vítr.",
    "Na koncertě hrála kapela, kterou zná většina našich společných přátel.",
    "Zítra ráno pojedeme na výlet do hor, vezmi si teplé boty.",
    "Šéfa žádal o schůzku, protože projekt má několik důležitých změn.",
    "Ráno jsem potkal známou lékařku, která mi poradila nový vitamínový preparát.",
    "Děti si hrály na zahradě, stavěly hrad z písku a větví společně.",
    "Koupili jsme čerstvé ryby, citrony a bylinky, aby večeře chutnala skvěle.",
    "Tři řemeslníci opravili starý plot, protože dřevo bylo úplně zhnilé.",
    "Na fotce byl kůň a párek turistů, kteří se smáli a fotili.",
    "V parku seděl stařec a krmil holuby kousky suchého pečiva každý večer.",
    "U doktorky jsem domluvil kontrolu očí na příští čtvrtek dopoledne s recepcí.",
    "Prosím napiš mi zprávu, až dorazíš domů a uděláš večerní úkol.",
    "Na tržišti jsem koupil koření, sýry, řepu a voňavé květiny pro maminku.",
    "Potřebuju správný adaptér, aby notebook fungoval na té zahraniční zásuvce.",
    "Doma nám kvete orchidej, takže každý týden kontroluji zalévání a hnojivo.",
    "Ten film byl napínavý, ale konec mi přišel trochu příliš předvídatelný.",
    "Na barvě sedačky zůstalo skvrn po kávě, takže jsem musel čistit.",
    "Moje kamarádka si pořídila nové kolo a pozvala mě na projížďku.",
    "Před domem stála taxík, řidič vypadal unaveně, ale ochotně nám pomohl.",
    "Ve zprávách zmínili dopravní omezení kvůli stavbě dálničního mostu v noci.",
    "Druhý pokoj malovali v sobotu i neděli, takže zápach barvy byl silný.",
    "Po práci jsme šli na pivo a debatovali o nadcházejícím víkendu společně.",
    "V knižním klubu jsme probírali román, jeho styl a hlavní postavy pečlivě.",
    "Na verandě seděla babička, pletla a povídala si s přáteli tiše.",
    "V zimě musíme uklidit sníh před domem, aby sousedé mohli projít pohodlně.",
    "Sousedé oznámili grilovačku v neděli, tak připravím salát a čerstvý chléb.",
    "Můj bratr včera spravil střechu, protože vítr poškodil staré tašky a žlaby.",
    "Když prší, rád sedím u okna a poslouchám kapky bubnovat na střechu.",
    "Ta restaurace má výborné dezerty, obzvlášť domácí štrúdl s vanilkovou zmrzlinou.",
    "Prosím dej pozor na prahy, jsou nízké, ale mohou způsobit zakopnutí.",
    "V autě hrála hudba, která mi připomněla léto a dlouhé jízdy s přáteli.",
    "Na vysoké škole vedla přednášku významná profesorka o historických pramenech okolí.",
    "Do pošty jsem šel odeslat balík, protože kamarád čekal zásilku celý týden.",
    "V sobotu odpoledne jsme navštívili trh, kde prodávali med, sýr a pečivo.",
    "Do kanceláře přišel nový kolega, usmál se a přivítal celý tým zdvořile.",
    "Maminka napeče koláče, které rozdá sousedům a pár přátelům z práce zítra.",
    "Pod mostem se schovali cyklisté před deštěm a chvíli čekali, až přejde.",
    "Na chodbě zněl hlasitý smích, děti hrály hru a běhaly sem a tam.",
    "Učitel vysvětloval látku pomalu, aby každý student pochopil zadání a úkol správně.",
    "Zítra mě čeká pohovor, tak si připravím dokumenty a vyprané košile pečlivě.",
    "Babička vyprávěla příběhy z mládí, vzpomínala na školy, kam chodila pěšky.",
    "Řeka byla po dešti rozbouřená, proto jsme zůstali opatrní a nešli blíž.",
    "V noci se ozvaly světla zdaleka, a tak jsme zkontrolovali bezpečnostní kamery doma.",
    "Po třech hodinách chůze jsme konečně našli úkryt před prudkým deštěm v chatě.",
    "Sousedé pořídili nového psa, chlupatého křížence, který se rád tulí a vrtí ocasem.",
    "Přečti si ten článek o energetických úsporách, je tam několik užitečných tipů.",
    "Chtěl bych objednat kytici rudých růží i s malou kartičkou a vzkazem.",
    "Na výletě jsme poslouchali průvodce, který nám popisoval staré legendy a památky.",
    "V nemocnici bylo rušno, sestry běhaly po chodbě a pacienti čekali na vyšetření.",
    "Na kole jsem projel město, potkal známé a koupil si čerstvé pečivo u pekaře.",
    "Ráda se učím cizí jazyky, protože rozšiřují obzory a otevírají nové možnosti práce.",
    "Ten recept je jednoduchý: smíchej mouku, vejce, mléko a špetku soli dohromady.",
    "Večer otevřeme okno, aby do bytu přišel čerstvý vzduch a vůně deště venku.",
    "Naše město má krásné náměstí s kašnou, stromy a několika kavárnami podél něj.",
    "Po obědě jsem si udělal krátkou siestu, protože jsem byl unavený z práce.",
    "V knihovně jsem si půjčil román o cestování, který čte mnoho lidí právě teď.",
    "Na festivalu hráli místní hudebníci, tančili jsme a ochutnali speciality z regionu.",
    "Doma jsem zahrabal semínka do květináče a každé ráno je pečlivě zaléval.",
    "Maminka volala z práce, že dorazí později, protože měla naléhavou schůzku.",
    "Včera jsme sledovali zápas a fandili našemu týmu, i když prohrál těsně.",
    "Naše třída plánuje výlet do muzea, kde budou interaktivní expozice pro děti.",
    "Chtěl bych koupit nové boty, ale musím nejprve najít vhodnou velikost pohodlnou.",
    "Na okraji lesa rostou borůvky, sbíráme je rádi a děláme z nich marmeládu.",
    "V kině promítali dokument o oceánech, který nás všechny hluboce zaujal a dojal.",
    "V zahradě zavládlo ticho, jen šuměl listí a hmyz bzučel kolem květin.",
    "Moje sestra studuje herectví a právě zkouší roli v novém divadelním představení.",
    "Ráno jsem našel na stole dopis, který mi poslal starý přítel z ciziny.",
    "V obchodě s nářadím koupím šrouby, nýty a nový klíč na demontáž skříně.",
    "Na koleji se sešli studenti, aby diskutovali projekt a rozdělili jednotlivé úkoly.",
    "Během dovolené jsme ochutnali místní speciality, koupili suvenýry a vyfotili pamětihodnosti.",
    "Na pláži jsme postavili vysoký hrad z písku a ozdobili ho mušlemi pečlivě.",
    "Uprostřed noci se rozsvítily lampy v zahradě, a tak jsme se v klidu vrátili.",
    "Ten pekař peče nejlepší buchty ve městě, chodí tam mnoho zákazníků denně.",
    "Ve škole připravili vystoupení, děti zpívaly písničky a všichni jim tleskali dlouho.",
    "Na recepci hotelu nám nabídli mapu města i tipy na zajímavé výlety hned.",
    "Do zahrady přišel zahradník, ostříhal keře a vysadil nové barevné trvalky s úsměvem.",
    "Měla bys zkontrolovat poštu, mohou tam být důležité dopisy od úřadů nebo banky.",
    "Táta slíbil, že postaví novou polici do dílny, ale nejprve musí koupit materiál.",
    "Na půdě jsme našli staré krabice s fotografiemi, které vyprávěly rodinné příběhy dlouhé.",
    "V horské chatě hráli kolem ohně a vyprávěli si strašidelné i veselé historky.",
    "Když se stmívá, světla v ulicích se rozsvěcují a lidé se pomalu rozcházejí domů.",
    "Studenti připravili reportáž o ochraně životního prostředí a natočili několik rozhovorů.",
    "V obchodě s elektronikou porovnáváme telefony, abychom vybrali ten nejlepší model rozumně.",
    "Na koncertě byl skvělý zpěvák, posluchači zpívali spolu a aplaus byl velmi dlouhý.",
    "Ráda peču chleba doma, protože ten domácí vůně vyvolává pocit útulnosti a klidu.",
    "Na ulici stál muž s deštníkem a hledal adresu, kterou mu někdo poradil.",
    "K večeru připravím polévku z čerstvé zeleniny, bude to lehké a zdravé jídlo.",
    "Má kamarádka právě porodila syna, oběma přejeme zdraví a hodně štěstí v životě.",
    "Na trhu jsme koupili tři jablka, hrušky a košík zručně pletených proutků.",
    "Po poradě jsme rozdělili úkoly, aby každý věděl, co má udělat přesně a včas.",
    "V obchodě mi při pokladně zapomněli vrátit drobné, musel jsem se jemně připomenout.",
    "Ráda si zazpívám písničku v autě, když jedu dlouhou cestu sama užívat klid.",
    "V kostele hrála varhanní hudba, lidé zpívali a atmosféra byla klidná a slavnostní.",
    "Na akademii představili nový projekt, který má pomoci studentům rozvíjet kreativitu a dovednosti.",
    "Doma jsme vyčistili okna, vyleštili nábytek a uspořádali květiny v pokojích hezky.",
    "Na jaře zasadíme strom před domem, aby poskytoval stín a zpříjemnil okolí zahrady.",
    "V kině byly fronty, ale nakonec jsme našli dobrá místa a film sledovali bez přerušení.",
    "Telefon zazvonil uprostřed noci a pochopitelně to byl důležitý hovor, který jsem nečekal.",
    "Na výstavě fotografií byly krásné snímky přírody, které mě opravdu oslovily a inspirují mě.",
    "Ráno jsem zaspal a musel jsem utíkat na tramvaj, abych stihl důležitou schůzku.",
    "V zahrádce rostou jahody, které denně kontroluji a sbírám, když jsou plně dozrálé.",
    "Ten hostitel nám nabídl čaj, koláče a příjemnou konverzaci o místních zvycích a řemeslech.",
    # Added / adjusted sentences to ensure dz, dž, ó appear at least three times
    "Na výstavě ochutnal host džem a čerstvý džus, oba mu moc chutnaly.",
    "Ve sklepení objevili podzemí se starými sklepy a několika historickými nálezy.",
    "V divadle zahrál sólově houslista krátké sólo, které diváci ocenili dlouhým potleskem.",
    "Tento obchod prodává džungle dekorace, ale také kvalitní domácí džem a džus.",
    "Při vykopávkách objevili podzemní chodby pod starým sídlem a mnoho mincí.",
    "Na festivalu hráli muzikanti sóla, a pak host přednesl další sólo improvizace.",
    "Děda opravoval podzemní kabely a nikdy neoznačil místo velkou oranžovou páskou pečlivě.",
    "Po cestě jsme zahlédli podzemní vchod, u něhož stála tichá cedule s informacemi."
]

def verify_sentence_integrity(sentences):
    from ING.PMR.stovka.phone_integrity_verifier import verify_phonemes

    ok, counts, details = verify_phonemes(sentences, min_count=3)
    print("All phonemes >=3? ", ok)
    print("Counts:", counts)
    print("Missing / underrepresented:", {k:v for k,v in counts.items() if v < 3})

if __name__ == "__main__":
    # for phone parsing: remove spaces and dashes, punctuations etc.
    verify_sentence_integrity(sentences)
    print("sentence count:", len(sentences))

